
Lesson 1 - Create a Repository
------------------------------
[[lesson-001]]

We will assume a Unix/Linux environment through these lessons. It is a bit impractical
to mirror all of the instructions for a Windows machine also, but perhaps in the future,
we'll update the commands log to include Windows examples.

To begin, let's make our very first repository. Here and throughout, the demo text
will include a leading `$` command prompt. This is partially to encourage you, the 
reader, to _type_ the examples rather than copy and paste them. At the end of each 
lesson though, you'll find a block of commands that reproduce the work we do in the
lesson that is formatted correctly for a simple copy and paste. You might like to build
up a script as you go along that replicates the state of your repositories so you 
can quickly recreate any state in the book for experimentation.

For our first demonstration, we're going to make a new repository. To keep the text
compact, I'll bundle commands onto one line sometimes in a way that may not seem 
totally natural - don't feel like you need to retype everything in exactly the same 
way.

----------------------------------------------
$ cd $HOME/tmp; mkdir scratch; cd scratch
$ echo 'some text' > foo.txt
$ echo 'more text' > bar.txt
$ git init
----------------------------------------------

This should produce the output:

----------------------------------------------
$ git init
Initialized empty Git repository in /Users/you/tmp/scratch/.git/
$ ls -a
./       ../      .git/    bar.txt  foo.txt
----------------------------------------------

What did we just do? We created a base repository - this is where we will 
efficiently store copies of our work. You can learn more by executing 
`git --help init`, but that could lead to information overload at this stage, 
so don't worry about that just yet.

Next, execute `git status`. You should see:

----------------------------------------------
$ git status
# On branch master
#
# Initial commit
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	bar.txt
#	foo.txt
nothing added to commit but untracked files present (use "git add" to track)
----------------------------------------------

We haven't committed anything yet, so we see the ``Initial commit'' message. Also 
note that we have ``untracked files.'' Git will only store the files you 
explicitly tell it to, and has flexible tools for helping you to ignore files you 
never want to commit (compiled binaries and libraries, for example).

Let's add a couple of files and make a commit.

----------------------------------------------
$ git add bar.txt 
$ git add foo.txt 
$ git status
# On branch master
#
# Initial commit
#
# Changes to be committed:
#   (use "git rm --cached <file>..." to unstage)
#
#	new file:   bar.txt
#	new file:   foo.txt
#
----------------------------------------------
Notice that ``adding'' the file did not actually commit to the repository. We 
simply told Git to track the file. 
This is an important part of the Git philosophy - we control access to the repository
and the content in it in separate steps. If you're used to a version control system
that doesn't subscribe to this approach, it can feel a bit awkward at first, but 
you'll see that it is useful to be able to separate those steps (and Git has ways of 
merging those steps if you'd like to).
Next, execute `git commit` and we will see this message:

----------------------------------------------

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
#
# Initial commit
#
# Changes to be committed:
#   (use "git rm --cached <file>..." to unstage)
#
# new file:   bar.txt
# new file:   foo.txt
#
----------------------------------------------
We have an opportunity to enter a message here logging the commit. Git actually 
won't let you commit without entering a log message. It is a good idea to always 
leave a concise, clear message. We'll see over the course of these lessons that 
Git strongly encourages a model of very frequent commits. You'll have the ability 
later to edit and compress your commits, so you don't need to worry about a 
cluttered commit history.

For now, type in something simple like: ``First commit of foobar.'' The default 
editor is Vim. If you don't know Vim, don't worry, we'll explain how to change the 
default editor in the next lesson. For now, just press ``i'' to enter vim's 
insert mode, type in your message, and then press the ESC key and follow it 
with ``:wq''.

Now, if we repeat `git status` we find nothing to commit:

----------------------------------------------
$ git status
# On branch master
nothing to commit, working directory clean
----------------------------------------------

But are we sure we did anything? Let's meet two more commands, `git log` and 
`git reflog`.

----------------------------------------------
$ git log
commit 8f4251f412089db0c1ba94b4e04baca50ef9ae64
Author: Gabriel Perdue <email@example.com>
Date:   Sun Oct 13 10:37:18 2013 -0500

    First commit of foobar.

$ git reflog
8f4251f HEAD@{0}: commit (initial): First commit of foobar.
----------------------------------------------

`git log` shows the commit logs. This is the ``official history,'' and is what you
would see if you checked the repository out from a remote server on a different
machine.

`git reflog` shows when branches change. We'll talk more about branches later, 
so for now think of it as a change history. The information is local to the 
repository, so if you work in one area for example, and then check the 
repository somewhere else, the two repositories will agree on the log but not
the reflog.

Even these simple commands are enough to get started with Git. You can create a
repository and use it to save incrememntal changes to your work. We don't know 
how to recover changes or how to replicate the repository on a remote server 
yet, but we'll get to that. In the meantime, you should practice these commands
by creating repositories for some of your current projects, adding some files, 
and saving your changes as you work. (Choose small projects since we haven't 
talked about how to manage the file addition process yet.)

Command Summary
~~~~~~~~~~~~~~~
[[summary-001]]

What have we done, and how would we reproduce our repository so far?
This is what we would enter on the command prompt:

--------------------------------
cd $HOME/tmp; mkdir scratch; cd scratch
echo 'some text' > foo.txt
echo 'more text' > bar.txt
git init
git add bar.txt 
git add foo.txt  
git commit
git status
git log
git reflog
--------------------------------

When we commit, our log message would be: ``First commit of foobar.''
The last three commands do not affect the repository but instead allow us to 
inspect its status.

