
Lesson 5 - Meeting Branches and Re-attaching our HEAD
-----------------------------------------------------
[[lesson-005]]

Now we know one way to retrieve an older version of the repository, but there is 
a problem - remember that ``detached HEAD'' message we ignored in the last lesson?
Well, we really ought to fix that before we go any further.

In order to do that we need to know what a _branch_ is. Without getting into too 
much depth, a branch is a way to experiment with large-scale changes safely. It
starts with a given version of your repository and you can make whatever changes 
you like while preserving an easy-to-retrieve version back where the branch 
started. 

Branches make collaboration much easier and safer. Suppose you are working on a 
major product. You have a stable, ``production'' version - this is the version 
you would ship to a customer or use for official tasks, etc. But you want to 
develop new features, and you'd like to be able to develop multiple new features 
in parallel, _and_ you would to save all your work in the repository. How do you
do this? 

In some older verion control systems (VCSs), you just made all of your new 
commits on top of the production version and protected your production version 
with a tag or some other marker. For simple projects this model might work, but 
it is easy to get in a state where you need to update the production version 
with one of the new features, but find it very difficult to manage all the 
changes sitting on top of it. Even worse, imagine you discover an important 
problem that only needs a small, quick fix after doing lots and lots of work 
on top of your production version. How do you include just that change? There 
are ways of course, but they're all messy. 

In Git, you solve this problem by creating a branch, which is a special version of 
the main repository. Creation and storage are very efficient - there is no need to 
worry about paying some extra cost for a branch. You do your work on the branch 
and when you are ready to include the feature, you _merge_ the branches. 
Other VCSs (CVS, SVN) certainly support branching, but they don't always do it 
well. Git was designed later than those programs and learned from their successes 
and failures. It was designed from the very beginning to work in a model with 
lots and lots of branches. It is very good at
managing those merges for you and has several different algorithms that make it 
effective and efficient.

How is this model different or better than the first model I described? Imagine
you have your production version of your project and several collaborators working
on independent feature branches. Perhaps some of them are even working on the same
branch. Their work doesn't interfere with each other and they can always save all
of their work to the repository. If you want to include a feature or a fix to a 
problem, you merge the branch into your production version. Once other features
are ready, they are merged next. This way you always have a stable, central
branch, called the +master+ branch in Git, but you are free to work on new
features without interfering with your stable main product.

So the best way to do idiomatic work in Git is to always work on a branch and
then, when the branch is ready, merge it into master. This might sound like 
extra work, but Git makes these tasks very easy and the payoff is spectacular.

Armed with all of that, let's go back and fix our detached HEAD.

--------------------
$ git branch feature_alpha
$ git checkout feature_alpha
Switched to branch 'feature_alpha'
$ git show-graph
* ef78473 Added yet another stable new feature
* 0fb1e51 Added another stable new feature
* 5d70af1 Added a stable new feature
* e346d22 Added some more content to bar.txt.
* 8f4251f First commit of foobar.
$ git diff master feature_alpha
diff --git a/foo.txt b/foo.txt
index 5eff915..a260796 100644
--- a/foo.txt
+++ b/foo.txt
@@ -1,4 +1,4 @@
 some text
 a stable new feature
 another stable new feature
-an experimental new feature
+yet another stable new feature
--------------------

First we created a new branch and then we checked it out - in other words, 
switched to it. You can combine these operations with 
`git checkout -b branch_name`. In general, you should give your branches 
descriptive names, but we don't have much to go on here, so I just named my 
branch +feature_alpha+.

Let's look at the reflog:

--------------------
$ git reflog
ef78473 HEAD@{0}: checkout: moving from ef7847367e547bd053bd1644cc4cacf9f159ca6a to 
ef78473 HEAD@{1}: commit: Added yet another stable new feature
0fb1e51 HEAD@{2}: checkout: moving from master to 0fb1e51
6ad5f77 HEAD@{3}: commit: Added an experimental new feature
0fb1e51 HEAD@{4}: commit: Added another stable new feature
5d70af1 HEAD@{5}: commit: Added a stable new feature
e346d22 HEAD@{6}: commit: Added some more content to bar.txt.
8f4251f HEAD@{7}: commit (initial): First commit of foobar.
--------------------

Now let's check out +master+ and take a look at it:

--------------------
$ git checkout master
Switched to branch 'master'
$ git show-graph
* 6ad5f77 Added an experimental new feature
* 0fb1e51 Added another stable new feature
* 5d70af1 Added a stable new feature
* e346d22 Added some more content to bar.txt.
* 8f4251f First commit of foobar.
--------------------

There's our experimental feature. Go ahead and switch back and forth a few times,
consulting the log and the reflog as you go. Notice how the reflog keeps track
of the checkouts but the log just shows what has been committed.

Now, recall that we didn't like our experimental feature, so let's get rid of 
it by forcing +master+ to agree with +feature_alpha+. Make sure you have checked
out +feature_alpha+, then:

--------------------
$ git branch -f master feature_alpha
$ git checkout master
Switched to branch 'master'
$ git show-graph
* ef78473 Added yet another stable new feature
* 0fb1e51 Added another stable new feature
* 5d70af1 Added a stable new feature
* e346d22 Added some more content to bar.txt.
* 8f4251f First commit of foobar.
--------------------

--------------------
$ git reflog
...
ef78473 HEAD@{5}: commit: Added yet another stable new feature
0fb1e51 HEAD@{6}: checkout: moving from master to 0fb1e51
6ad5f77 HEAD@{7}: commit: Added an experimental new feature
0fb1e51 HEAD@{8}: commit: Added another stable new feature
...
--------------------

--------------------
$ git show-graph
* ef78473 Added yet another stable new feature
* 0fb1e51 Added another stable new feature
* 5d70af1 Added a stable new feature
* e346d22 Added some more content to bar.txt.
* 8f4251f First commit of foobar.
--------------------

There is no record of the commit in the official history! This means your 
collaborators will have a hard time finding it. What if _you_ want it back?

The best way to solve this problem is to always develop on a branch to begin
with. We'll start doing that in the next lesson.


Command Summary
~~~~~~~~~~~~~~~
[[summary-005]]

What have we done, and how would we reproduce our repository so far?
We would first follow the summary from the previous section <<summary-004>>.
Then, we would enter:

-------------------
git branch feature_alpha
git checkout feature_alpha
git branch -f master feature_alpha
git checkout master
-------------------

